name: CI-CD
on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o Codigo
        uses: actions/checkout@v4.2.2
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Construcao e Envio da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: danieldevpy/fake-shop-desafio:v2
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Código"
      - run: echo "Condigurar o kubeconfig"
      - run: echo "Executar o apply"
    
