name: CI-CD
on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Executar o Docker Build"
      - run: echo "Enviar a imagem Docker para o Docker Hub"
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Código"
      - run: echo "Condigurar o kubeconfig"
      - run: echo "Executar o apply"
    
